version: "3.9"

services: 
    db:
        image: postgres:13
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        ports:
          - "5432:5432"
        restart: always
        volumes:
          - pgdata:/var/lib/postgresql/data
    
    pgadmin:
        image: dpage/pgadmin4
        environment:
          - PGADMIN_DEFAULT_EMAIL=admin@example.com
          - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
          - "80:5050"
        logging:
            driver: none
        ports:
            - "5050:80"
        restart: always
        volumes:
          - pgadmindata:/var/lib/pgadmin
        depends_on:
          - db

    web:
        build: .
        command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        ports:
          - "8000:8000"
        restart: always
        volumes: 
          - .:/code
        depends_on:
          - db

volumes: 
  pgdata:
  pgadmindata:
